blank_issues_enabled: false
contact_links:
  - name: ⚠ Feature request
    url: https://github.com/Tyrrrz/Onova/wiki/Maintenance-mode
    about: Sorry, but this project is in maintenance mode and no longer accepts new feature requests.
  - name: 🗨 Discussions
    url: https://github.com/Tyrrrz/Onova/discussions/new
    about: Ask and answer questions.